[tox]
isolated_build = true
skip_missing_interpreters = true
parallel_show_output = true
envlist =
    py{312,313,314}-dj{52,60}

[pytest]
testpaths = test
django_find_project = true
filterwarnings =
    error
DJANGO_SETTINGS_MODULE=demo_proj.settings
addopts =
  --tb=short

[testenv]
skip_install = true
description = Run tests in {envname} environment
setenv =
    PYTHONHASHSEED=0
    PYTHONPATH={toxinidir}:demo
    PYTHONBREAKPOINT=ipdb.set_trace
commands =
    pip install -e .
    pytest {posargs}
deps =
    pytest
    pytest-django
    dj52: Django>=5.2,<6.0
    dj60: Django>=6.0,<6.1

[testenv:coverage]
description = Run test coverage and display results
basepython = python3.12
deps =
    {[testenv]deps}
    coverage
    pytest-cov
whitelist_externals =
    echo
commands =
    pip install -e .
    pytest --cov-config .coveragerc --cov-report html --cov-report term --cov=travel
    echo HTML coverage report: {toxinidir}/htmlcov/index.html

[flake8]
# E128: continuation line under-indented for visual indent
# E124: closing bracket does not match visual indentation
# E126: continuation line over-indented for hanging indent
# W503: line break occurred before a binary operator
# W504 line break after binary operator
ignore = E128,E124,E126,W503,W504
max-line-length = 100
exclude =
    .git,
    __pycache__,
    */migrations/*

[coverage:run]
omit =
    */migrations/*

[gh-actions]
python =
    3.12: py312
    3.13: py313
    3.14: py314
