# Generated by Django 2.0.2 on 2018-03-06 15:07

from django.db import migrations

MAGIC_A = 127462

CODES = {
    chr(ord('A') + i): chr(MAGIC_A + i)
    for i in range(26)
}


def flag_emoji(iso):
    i, j = iso.upper()
    return CODES[i] + CODES[j]


def populate_emojis(apps, schema_editor):
    EntityType = apps.get_model('travel', 'TravelEntityType')
    Entity = apps.get_model('travel', 'TravelEntity')

    co_type = EntityType.objects.filter(abbr='co')
    if co_type:
        co_type = co_type[0]
        for e in Entity.objects.filter(type=co_type).select_related('flag'):
            if e.flag:
                e.flag.emoji = flag_emoji(e.code)
                e.flag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20180216_1854'),
    ]

    operations = [migrations.RunPython(populate_emojis)]
