# Generated by Django 2.1.2 on 2018-10-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20181014_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelentity',
            name='category',
        ),
        migrations.RemoveField(
            model_name='travelentity',
            name='geonameid',
        ),
        migrations.AddField(
            model_name='travelentity',
            name='alt_code',
            field=models.CharField(db_index=True, default='', max_length=8, blank=True),
        ),
        migrations.AlterField(
            model_name='travelentity',
            name='code',
            field=models.CharField(db_index=True, max_length=8),
        ),
    ]
