# Generated by Django 3.0.1 on 2020-02-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20181022_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelentity',
            options={'ordering': ('name',), 'verbose_name_plural': 'travel entities'},
        ),
        migrations.AddField(
            model_name='travelentity',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='travelentity',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
