# Generated by Django 4.2.8 on 2024-01-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0009_alter_travelalias_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelentityinfo",
            name="intregion",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="travelentityinfo",
            name="region",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="travelentityinfo",
            name="subregion",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
